spring:  
  application:
    name: "Restaurant Microservice"
  datasource:
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:testdb"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
    
server:
  port: 8081